// <auto-generated />
using System;
using MedicalClinicQueue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedicalClinicQueue.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MedicalClinicQueue.Models.ServiceItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastTimestamp");

                    b.Property<string>("Name");

                    b.Property<int>("QueueCount");

                    b.HasKey("Id");

                    b.ToTable("ServiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
